import Navbar from "@/components/Navbar"
import InputNavbar from "@/components/InputNavbar"

import type { Metadata } from "next"
import { Red_Hat_Text } from "next/font/google"
import "./globals.css"

const redHatText = Red_Hat_Text({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={redHatText.className}>
        <Navbar />
        <InputNavbar />
        {children}
      </body>
    </html>
  )
}
