import Header from "@/components/Header";

import type { Metadata } from "next";
import { Red_Hat_Text } from "next/font/google";
import { getCountries } from "@/lib/data-service";

import "./globals.css";
import "react-day-picker/dist/style.css";

const redHatText = Red_Hat_Text({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const fetchCountries = await getCountries();

    let countries = fetchCountries.map((el) => ({
        name: el.name.common,
    }));

    return (
        <html lang="en">
            <body className={redHatText.className}>
                <Header countries={countries} />
                {children}
            </body>
        </html>
    );
}
