import Header from "@/components/Header";

import type { Metadata } from "next";
import { Red_Hat_Text } from "next/font/google";
import "./globals.css";
import "react-day-picker/dist/style.css";

const redHatText = Red_Hat_Text({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={redHatText.className}>
                <Header />
                {children}
            </body>
        </html>
    );
}
